#!/usr/bin/env python3
"""Combine subproject portfolio markdown files into the root PORTFOLIO.md."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
import posixpath
import re


PREFERRED_FILENAMES = ("portfolio.md", "Portfolio.md", "PORTFOLIO.md")
EXCLUDED_DIRS = {".git", "__pycache__", ".venv", "venv", "node_modules"}


def is_external_path(path: str) -> bool:
    """Return True for URLs and anchors that should not be rewritten."""
    lowered = path.lower()
    return lowered.startswith(("http://", "https://", "data:", "mailto:", "#"))


def rewrite_image_path(path: str, source_dir: str) -> str:
    """Rewrite image path so it resolves from the repository root."""
    path = path.strip()
    if not path or is_external_path(path):
        return path

    match = re.match(r"^([^?#]*)([?#].*)?$", path)
    if match is None:
        return path

    raw_path = match.group(1)
    suffix = match.group(2) or ""

    # Already rooted at the correct source directory.
    if raw_path.startswith(f"{source_dir}/"):
        return path

    if raw_path.startswith("/"):
        rewritten = posixpath.normpath(posixpath.join(source_dir, raw_path.lstrip("/")))
    else:
        rewritten = posixpath.normpath(posixpath.join(source_dir, raw_path))

    return f"{rewritten}{suffix}"


def rewrite_image_paths_in_markdown(content: str, source_dir: str) -> str:
    """Rewrite image paths in markdown and HTML image tags."""

    def markdown_image_replacer(match: re.Match[str]) -> str:
        alt_text = match.group(1)
        inner = match.group(2).strip()

        if not inner:
            return match.group(0)

        if inner.startswith("<") and ">" in inner:
            closing_index = inner.find(">")
            image_path = inner[1:closing_index].strip()
            trailing = inner[closing_index + 1 :].strip()
            rewritten = rewrite_image_path(image_path, source_dir)
            if trailing:
                return f"![{alt_text}](<{rewritten}> {trailing})"
            return f"![{alt_text}](<{rewritten}>)"

        parts = inner.split(maxsplit=1)
        image_path = parts[0]
        trailing = parts[1] if len(parts) > 1 else ""
        rewritten = rewrite_image_path(image_path, source_dir)
        if trailing:
            return f"![{alt_text}]({rewritten} {trailing})"
        return f"![{alt_text}]({rewritten})"

    def html_image_replacer(match: re.Match[str]) -> str:
        quote = match.group(1)
        image_path = match.group(2)
        rewritten = rewrite_image_path(image_path, source_dir)
        return f"src={quote}{rewritten}{quote}"

    content = re.sub(r"!\[([^\]]*)\]\(([^)]+)\)", markdown_image_replacer, content)
    content = re.sub(r"src\s*=\s*([\"'])([^\"']+)\1", html_image_replacer, content)
    return content


def find_portfolio_file(project_dir: Path) -> Path | None:
    """Return the first portfolio markdown file in a project directory."""
    for filename in PREFERRED_FILENAMES:
        candidate = project_dir / filename
        if candidate.is_file():
            return candidate

    # Fallback: search recursively for any case variation of portfolio.md.
    for candidate in sorted(project_dir.rglob("*.md")):
        if candidate.name.lower() == "portfolio.md":
            return candidate

    return None


def get_subprojects(root_dir: Path) -> list[Path]:
    """Return top-level directories that are likely project folders."""
    return sorted(
        [
            path
            for path in root_dir.iterdir()
            if path.is_dir() and path.name not in EXCLUDED_DIRS and not path.name.startswith(".")
        ],
        key=lambda path: path.name.lower(),
    )


def build_combined_markdown(root_dir: Path) -> str:
    """Generate merged markdown from all subproject portfolio files."""
    lines: list[str] = [
        "# Computer Science Y1 P3 Combined Portfolio",
        "",
        "This file is auto-generated by combine_portfolios.py.",
        " - master repository: https://github.com/pop9459/P3-Portfolio",
        f" - updated at: {datetime.now().isoformat(timespec='seconds')}",
        "",
    ]

    subprojects = get_subprojects(root_dir)
    if not subprojects:
        lines.extend(["No subprojects were found.", ""])
        return "\n".join(lines)

    for project_dir in subprojects:
        portfolio_file = find_portfolio_file(project_dir)

        if portfolio_file is None:
            lines.extend([f"_No portfolio.md found in {project_dir.name}._", ""])
            continue

        relative_path = portfolio_file.relative_to(root_dir)
        content = portfolio_file.read_text(encoding="utf-8", errors="replace").strip()
        source_dir = relative_path.parent.as_posix()
        content = rewrite_image_paths_in_markdown(content, source_dir)

        lines.append(f"Source: {relative_path.as_posix()}")
        lines.append("")
        if content:
            lines.append(content)
            lines.append("")
        else:
            lines.extend(["_Portfolio file exists but is empty._", ""])

    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    root_dir = Path(__file__).resolve().parent
    output_file = root_dir / "PORTFOLIO.md"

    combined_markdown = build_combined_markdown(root_dir)
    output_file.write_text(combined_markdown, encoding="utf-8")

    print(f"Updated {output_file}")


if __name__ == "__main__":
    main()
