#!/usr/bin/env python3
"""Combine subproject portfolio markdown files into the root PORTFOLIO.md."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path


PREFERRED_FILENAMES = ("portfolio.md", "Portfolio.md", "PORTFOLIO.md")
EXCLUDED_DIRS = {".git", "__pycache__", ".venv", "venv", "node_modules"}


def find_portfolio_file(project_dir: Path) -> Path | None:
    """Return the first portfolio markdown file in a project directory."""
    for filename in PREFERRED_FILENAMES:
        candidate = project_dir / filename
        if candidate.is_file():
            return candidate

    # Fallback: search recursively for any case variation of portfolio.md.
    for candidate in sorted(project_dir.rglob("*.md")):
        if candidate.name.lower() == "portfolio.md":
            return candidate

    return None


def get_subprojects(root_dir: Path) -> list[Path]:
    """Return top-level directories that are likely project folders."""
    return sorted(
        [
            path
            for path in root_dir.iterdir()
            if path.is_dir() and path.name not in EXCLUDED_DIRS and not path.name.startswith(".")
        ],
        key=lambda path: path.name.lower(),
    )


def build_combined_markdown(root_dir: Path) -> str:
    """Generate merged markdown from all subproject portfolio files."""
    lines: list[str] = [
        "# Y1P3 Computer Science Combined Portfolio",
        "",
        "This file is auto-generated by combine_portfolios.py.",
        " - master repository: https://github.com/pop9459/P3-Portfolio",
        f" - updated at: {datetime.now().isoformat(timespec='seconds')}",
        "",
    ]

    subprojects = get_subprojects(root_dir)
    if not subprojects:
        lines.extend(["No subprojects were found.", ""])
        return "\n".join(lines)

    for project_dir in subprojects:
        lines.extend([f"## {project_dir.name}", ""])
        portfolio_file = find_portfolio_file(project_dir)

        if portfolio_file is None:
            lines.extend(["_No portfolio.md found in this subproject._", ""])
            continue

        relative_path = portfolio_file.relative_to(root_dir)
        content = portfolio_file.read_text(encoding="utf-8", errors="replace").strip()

        lines.append(f"Source: {relative_path.as_posix()}")
        lines.append("")
        if content:
            lines.append(content)
            lines.append("")
        else:
            lines.extend(["_Portfolio file exists but is empty._", ""])

    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    root_dir = Path(__file__).resolve().parent
    output_file = root_dir / "PORTFOLIO.md"

    combined_markdown = build_combined_markdown(root_dir)
    output_file.write_text(combined_markdown, encoding="utf-8")

    print(f"Updated {output_file}")


if __name__ == "__main__":
    main()
